### ISSUE TITLE
Предлагаю изменить цель проекта и вектор целевой аудитории

### ISSUE THREAD

**Issue by MammutAlex** [PycckuuJS/pycckuu-loader#12]
Я подумал, где бы такой вид был актуальным. И пришла мысль, что именно такой он будет хорош в образовательных целях, к примеру педагог пишет рабочий код, а все дублируется еще и на языке аборигенов(русский, украинский, французский). Таким образом легче понять аналогию и перестать смотреть как на магию. Это можно сделать плагином на sublimetext или как-то иначе, как вам такая идея?

**Comment by SPAHI4** [comment]
- лучше это сделать как трансформер к бабелу
