### ISSUE TITLE
Что-то надо решать с логикой

### ISSUE THREAD

**Issue by JWo1F** [PycckuuJS/pycckuu-loader#7]
Добрый вечер, бояре!
Попытались мы внедрить сей продукт в наш проект. Выкатили все в продакшн и полетели на нас жалобы от пользователей, что все сломалось и ничего не работает. Начали разбираться, поняли, что если написать так:

``` javascript
пер псевдомассивчик;

если(Math.random() > 0.5) {
  псевдомассивчик = [1,2,3];
} иначе {
  псевдомассивичк = {
    длина: 7,
    "0": 1,
    "1": 1,
    "2": 1,
    "3": 1,
    "4": 1,
    "5": 1,
    "6": 1
  };
}

внимание(псевдомассивчик.длина);
```

то в 50% случаев (когда по воле случая управление передается в блок "иначе") все падает, так как тут не должно быть преобразования длина => length.

Грусть, тоска и печаль. Откатили все назад на бесовский язык. Ждем фикса!

**Comment by mdunaev** [comment]
Добрый день! Вы немного не правы, все работает как и ожидается. В английской версии ЯваСкрипта вы не можете использовать ключевые слова для обозначения ключей в ассоциативном массиве. Та же логика и в российском, не стОит называть ключи в массиве русскими зарезервированными словами.

**Comment by JWo1F** [comment]
Да ну?

```
{
  "length": 12
}
```

Вполне работает, @mdunaev 
Да и length не является зарезервированным словом.
