### ISSUE TITLE
Как подключить русский JS?

### ISSUE THREAD

**Issue by filtr-slov** [PycckuuJS/pycckuu-loader#8]
Напишите в ПрочитиМеня.текст как подключить русскийJS к своему проекту?

**Comment by nomoreangels** [comment]
Пример конфигурации для Сетьпакета есть в ПрочтиМеня и он довольно красноречив: 
`{ test: /\.яс$/, loader: "pycckuu" }`
- Следует установить webpack и pycckuu-loader: 

```
npm install -S webpack
npm install -S pycckuu-loader
```
- Создать webpack.config.js как в примере
- Написать какой-нибудь скрипт
- Запустить webpack и получить result.js
- ???
- Профит (нет)

Загрузчиком будут обрабатываться файлы с расширением .яс (можно сменить на другое).
